# ========================================================
# 1. НОВЫЙ ПРОЕКТ (Сайт-визитка) — Срабатывает строго по домену
# ========================================================
server {
    listen 80;
    server_name alexander-python-backend-fastapi.ru www.alexander-python-backend-fastapi.ru;

    # 1. Раздача фронтенда (Статический index.html)
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    # 2. Раздача статики ДЖАНГО АДМИНКИ (ИСПРАВЛЕН ПУТЬ)
    # Административная статика Django всегда лежит в подпапке /static/admin/
    location /static/admin/ {
        alias /app/backend_static/admin/;
    }

    # 3. Раздача загружаемых медиафайлов (Аватарки, превью проектов)
    location /media/ {
        root /app; # Nginx сам прибавит к /app запрос /media/catalog/image/...
        expires 7d;
    }

    # 4. Проксирование запросов к API и Админке внутрь контейнера Django к Gunicorn
    location ~ ^/(api|admin) {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# ========================================================
# 2. СТАРЫЙ ПРОЕКТ (LogiTrack) — Срабатывает по чистому IP сервера
# ========================================================
server {
    # listen 80 default_server означает, что этот блок поймает любой запрос,
    # который не подошёл под имя домена выше (то есть запрос по прямому IP)
    listen 80 default_server;
    server_name _;

    location / {
        # Перенаправляем трафик в контейнер старого бэкенда по имени его сервиса
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}