# Редирект HTTP -> HTTPS (домен)
server {
    listen 80;
    server_name alexander-python-backend-fastapi.ru www.alexander-python-backend-fastapi.ru;
    return 301 https://$host$request_uri;
}

# HTTPS для домена
server {
    listen 443 ssl;
    http2 on;
    server_name alexander-python-backend-fastapi.ru www.alexander-python-backend-fastapi.ru;

    ssl_certificate     /etc/letsencrypt/live/alexander-python-backend-fastapi.ru/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/alexander-python-backend-fastapi.ru/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location /static/admin/ {
        alias /app/backend_static/admin/;
    }
    location /media/ {
        root /app;
        expires 7d;
    }
    location ~ ^/(api|admin) {
        proxy_pass http://backend:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

# LogiTrack по IP — остаётся на 80
server {
    listen 80 default_server;
    server_name _;
    location / {
        proxy_pass http://web:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}