# Generated by Django 6.0.7 on 2026-07-31 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Имя")),
                (
                    "title",
                    models.CharField(
                        max_length=150, verbose_name="Позиция (Заголовок)"
                    ),
                ),
                ("about", models.TextField(verbose_name="О себе")),
                (
                    "avatar",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile/", verbose_name="Фото"
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                ("phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("telegram", models.CharField(max_length=50, verbose_name="Telegram")),
                ("github", models.URLField(verbose_name="GitHub")),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=150, verbose_name="Название проекта"),
                ),
                ("description", models.TextField(verbose_name="Описание проекта")),
                (
                    "features",
                    models.TextField(
                        verbose_name="Что было сделано (через точку с запятой)"
                    ),
                ),
                (
                    "tech_stack",
                    models.CharField(max_length=200, verbose_name="Стек технологий"),
                ),
                (
                    "test_coverage",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Покрытие тестами (%)"
                    ),
                ),
                ("github_url", models.URLField(verbose_name="Ссылка на GitHub")),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="projects/",
                        verbose_name="Превью проекта",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Название технологии"),
                ),
                (
                    "level",
                    models.PositiveIntegerField(verbose_name="Уровень владения (%)"),
                ),
            ],
        ),
    ]
