# Generated by Django 6.0.7 on 2026-08-03 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_alter_profile_avatar_alter_project_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="about_en",
            field=models.TextField(null=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="profile",
            name="about_ru",
            field=models.TextField(null=True, verbose_name="О себе"),
        ),
        migrations.AddField(
            model_name="profile",
            name="title_en",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Позиция (Заголовок)"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="title_ru",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Позиция (Заголовок)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="description_en",
            field=models.TextField(null=True, verbose_name="Описание проекта"),
        ),
        migrations.AddField(
            model_name="project",
            name="description_ru",
            field=models.TextField(null=True, verbose_name="Описание проекта"),
        ),
        migrations.AddField(
            model_name="project",
            name="features_en",
            field=models.TextField(
                null=True, verbose_name="Что было сделано (через точку с запятой)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="features_ru",
            field=models.TextField(
                null=True, verbose_name="Что было сделано (через точку с запятой)"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack_en",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Стек технологий"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="tech_stack_ru",
            field=models.CharField(
                max_length=200, null=True, verbose_name="Стек технологий"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_en",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Название проекта"
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="title_ru",
            field=models.CharField(
                max_length=150, null=True, verbose_name="Название проекта"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_en",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Название технологии"
            ),
        ),
        migrations.AddField(
            model_name="skill",
            name="name_ru",
            field=models.CharField(
                max_length=50, null=True, verbose_name="Название технологии"
            ),
        ),
    ]
