# Generated by Django 6.0.7 on 2026-08-03 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_profile_about_en_profile_about_ru_profile_title_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="name_en",
            field=models.CharField(max_length=100, null=True, verbose_name="Имя"),
        ),
        migrations.AddField(
            model_name="profile",
            name="name_ru",
            field=models.CharField(max_length=100, null=True, verbose_name="Имя"),
        ),
    ]
